version: "3.9"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      HOST: db
      PORT: 3306
      USER: root
      PASSWORD: _________
      DB_NAME: db
  db:
    image: mysql
    container_name: "MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: _________
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro